### PR TITLE
Update automerge, re-add save decision

### PR DESCRIPTION
**Pull request by gterzian**
This re-adds the decision to do a full vs incremental saves, and does so using automerge 0.5.0. 

This is a separate branch because it appears bumping automerge breaks the integration, so I've left the other branch alone for now.

### CODE REVIEW

**Comment by issackelly** [comment]
I don't think that I understand the interplay between "patches since last save" and compaction.

IIUC, compaction saves the entire document as a snapshot and destroys all previous snapshots and incrementals, so this would only occur if there were > 10 patches _before_ an incremental? 

Shouldn't it only be reset after compacting?

**Comment by gterzian** [comment]
> Shouldn't it only be reset after compacting?

Yes you're right, I think [this](https://github.com/automerge/spanreed/pull/21/files#diff-8a44ff48a251d03d58e6d3c73e8664553e2aa7b2a925641dd6c3d2f81c0d2e11R751) should be moved to the branch that does compaction.

Also, we may want to add logic that does a compaction on the first save? Or can the first one be incremental?

**Comment by issackelly** [comment]
I have a branch that allows compaction on the first save, but first being incremental isn't a big deal as long as we don't throw it away. I'll try to separate out those commits as separate PRs

**Comment by issackelly** [comment]
> Yes you're right, I think [this](https://github.com/automerge/spanreed/pull/21/files#diff-8a44ff48a251d03d58e6d3c73e8664553e2aa7b2a925641dd6c3d2f81c0d2e11R751) should be moved to the conditional branch that does compaction.

Yeah I agree, thanks.

**Comment by issackelly** [comment]
Here it is: https://github.com/automerge/spanreed/commit/faa58e9f30038e53cc064d5dbf4584d8234ebd4c

I have a ~junk PRs that shouldn't be merged here, but it's where I'm collecting all the changes I need to get this into production, we can make tiny PRs as appropriate.

**Comment by issackelly** [comment]
Here's a commit that addresses the `patches_since` https://github.com/automerge/spanreed/pull/50/commits/962b38c27fad462dd2bc99b2e61bd3d14cb6fcf6

**Comment by issackelly** [comment]
I think this introduces a deadlock in `note_changes` -- when it is set to `true` the tests pass, but with this implementation, they hang.

What about a thread local that simply counts the number of times that `save_document` was run?

**Comment by gterzian** [comment]
> I think this introduces a deadlock in `note_changes` -- when it is set to `true` the tests pass, but with this implementation, they hang.
> 
> What about a thread local that simply counts the number of times that `save_document` was run?

That test was badly written :)

I have pushed a fix to your `compaction` branch. @issackelly

**Comment by gterzian** [comment]
@issackelly 

Ok, I have pushed a fix. 

This was the race condition:

In the handling of the [`RepoEvent::DocChange`](https://github.com/automerge/spanreed/blob/f95edd1f548f3822dcced04607bea794d8887d6e/src/repo.rs#L1195), we would only handle the event if `note_changes` returned `true`. 

This would be `false` if the backend had saved the document after the local change had been committed, but before the `RepoEvent::DocChange` had been received, which would happen if the save had been triggered by an incoming sync message. 

In other words, when doing the save in response to the incoming sync message, the current state of the document already included the last local change, so the subsequent `RepoEvent::DocChange` would be ignored. 

Ignoring the subsequent even resulted in not sending out any sync messages for that latest change(which had been saved already). 

I've pushed a change to your branch that in such a case only skips the saving, not the sending out of sync messages. 

In general there is a complication around changes to the local document, which happen via the lock around the shared doc, and event handling around those changes. Another example was waking up handles on `changed`. 

I think the current fix is ok, although it may have unintended consequences. It may make sense to at some point separate out the `last_heads` concept between one used for saving only, and one used for other things(sending out sync, waking up on `changed`). Tracked in

**Comment by issackelly** [comment]
Thanks! Good catch and fix on this. I left a note about the read_lock on note_changes in #51 but we can continue there.

**Comment by alexjg** [comment]
Superceded by #58

**Pull request closed without merging**
